### ISSUE TITLE
MailChimp->success() returns incorrect value on successful POST

### ISSUE THREAD

**Issue by prsrichard** [drewm/mailchimp-api#106]
Hi there,

I like using your wrapper; fine work!
But when I try to use the post-method to perform an action (schedule campaign), the success() method always says, it was unsuccessful. Although the scheduling was successful and is visible within mailchimp dashboard.

There is an small bug in the code within the 'formatResponse' method, I think.

If any of the actions on a campaign is called via post method, the response body is not set.
Therefore it gets recognized as 'not successful request'.

See in documentation (Example responses):
http://developer.mailchimp.com/documentation/mailchimp/reference/campaigns/#action-post_campaigns_campaign_id_actions_schedule

edit:
I just added this as workaround. Works for me:

```
        if (!empty($response['body'])) {
           ...
            return $d;
        }else{
	        if(!empty($response['headers']) && isset($response['headers']['http_code']) && ($response['headers']['http_code'] == 204)){
		        return true;
	        }
        }

**Comment by drewm** [comment]
Should now be fixed - just testing and will tag a release.

**Comment by freekmurze** [comment]
Is this fix already present in a tagged version?

**Comment by drewm** [comment]
Yes, v2.2.2 from last week should do it.

**Comment by freekmurze** [comment]
Cool, thanks!

Friendly tip: you could opt to [keep a changelog](http://keepachangelog.com/) so users of your package can look up what was added/fixed in a version.

**Comment by ivanvermeyen** [comment]
Hello,

I just double checked I'm using version (2.2.2), but `success()` still returns false after subscribing someone.

The last error is:
"Unknown error, call getLastResponse() to find out what happened."

The last response includes a header array with a http code of 200 and a json body with a status of "subscribed"...

I tracked the problem down to [this check](https://github.com/drewm/mailchimp-api/blob/v2.2.2/src/MailChimp.php#L316-L318) that returns the status from the body instead of the http code from the header. Therefor [this check](https://github.com/drewm/mailchimp-api/blob/v2.2.2/src/MailChimp.php#L294-L297) fails...

I noticed that the master branch checks the header first, but this change doesn't seem to be tagged yet ;)
