### ISSUE TITLE
is already a list member

### ISSUE THREAD

**Issue by joSFD** [drewm/mailchimp-api#210]
Hi !

I have two different lists (A & B).
It seems i cannot post an email address on list B if it exists on list A.

```
$list_id = 'xxxlist_Bxxx';
$response_array = $MailChimp->post("lists/$list_id/members", [
	'email_address' => $email,
	'status'        => 'subscribed'
]);
```
I get this response :
"_xxx@xxx.net is already a list member. Use PUT to insert or update list members._"

When i try a PUT, i get this reponse :
"_The requested method and resource are not compatible. See the Allow header for this resource's available methods._"

Any idea ?

Thank you !
Johan

**Comment by terrymun** [comment]
If you read the [MailChimp API](https://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/#), you cannot use `PUT` to add a member (it is used to update details of an existing member identified using MD5-hash of his/her email). Only `POST` is allowed.

**Comment by jakepm** [comment]
Hi there, I'm having this same issue and am not quite sure how to use this API wrapper to identify if an email address already exists in any of our lists.

I understand that if the user is already subscribed to one of our lists, then I have to use the patch() method instead of post(). However, I cannot work out how to find this out. I tried $MC->get("lists/$list_id/members/$sub_hash"); but this just throws an error if the user doesn't exist, plus it doesn't allow me to check that the user exists in *any* of our lists.

Please could you give some further guidance, ideally with a code sample?

**Comment by nietonfir** [comment]
@jakepm Afaik you cannot check if a user exists in any list, but this is how the MailChimp API works. You can always try it out in the [playground](https://us1.api.mailchimp.com/playground/).

As for the check this should get you going (reduced for the sake of brevity):
```php
$listMembersUrl = sprintf('lists/%s/members', $listId);
$hash = $mailChimp->subscriberHash($email);

$mailChimp->get(sprintf('%s/%s', $listMembersUrl, $hash));

if ($mailChimp->success()) {
    $mailChimp->patch(sprintf('%s/%s', $listMembersUrl, $hash), array(
        // whatever should be updated
    );
} else {
    $mailChimp->post($listMembersUrl, array(
        // create a user
    );
}
```

@drewm Can be closed since not a library issue imho.

**Comment by Jossnaz** [comment]
I have the same weird situation

btw the assumption you cannot use PUT to add a member is wrong @terrymun at least afaik. 

http://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/#edit-put_lists_list_id_members_subscriber_hash

reads:

> Add or update a list member
> PUT /lists/{list_id}/members/{subscriber_hash}
> Add or update a list member.


Note: I'm not even using your library (my bad for only discovering it now, not sure how I did not find it earlier?!). Sadly it is too late now to adopt your lib. 

It seems to me that eventually mailchimp returns a wrong error. The exact same code written by me works for one member, but not for the other. In case I figure out what it is, I will let you know.

**Comment by Jossnaz** [comment]
ok seems that the email was added like this, note case sensitivity:

`TestX@hotmail.com`


when then running the PUT request to update said email I get a 
```
'type' => string(77) "http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/"
'title' => string(13) "Member Exists"
'status' => integer400
→'detail' => string(86) "TestX@hotmail.com is already a list member. Use PUT to insert or update list me…"
TestX@hotmail.com is already a list member. Use PUT to insert or update list members.
'instance' => string(36) "xxxxx-xxxxx-xxxx-xxxx-xxxx"
```

which is silly, because PUT is what I used.

What I found out is that before running the PUT request, you need to lowercase the email

running the exact same PUT request with email

`testx@hotmail.com` works fine.

A bug in mailchimp that you certainly have noticed as well already... but leaving here anyway in case it helps someone.

**Comment by pdbreen** [comment]
Excerpt from Mailchimp API Doc - https://developer.mailchimp.com/documentation/mailchimp/guides/manage-subscribers-with-the-mailchimp-api/

> Identify Subscribers
> In previous versions of the API, we exposed internal database IDs eid and leid for emails and list/email combinations. In API 3.0, we no longer use or expose either of these IDs. Instead, we identify your subscribers by the MD5 hash of the lowercase version of their email address so you can easily predict the API URL of a subscriber’s data.
> 
> For example, to get the MD5 hash of the email address Urist.McVankab@freddiesjokes.com, first convert the address to its lowercase version: urist.mcvankab@freddiesjokes.com. The MD5 hash of urist.mcvankab@freddiesjokes.com is 62eeb292278cc15f5817cb78f7790b08.

**Comment by Jossnaz** [comment]
hmm ok thanks for the clarfication

still, the error message "Use PUT instead" is wrong, and very well is considered a bug by me.

**Comment by drewm** [comment]
That message is from MailChimp, not from this library.

**Comment by solarin** [comment]
same problem, solved using PUT to this address:

$dataCenter = substr($apiKey,strpos($apiKey,'-')+1);
'https://' . $dataCenter . '.api.mailchimp.com/3.0/lists/' . $listID . '/members/' . $memberID;

**Comment by solarin** [comment]
remember that MailChimp doesn't like empty merge_fields. so, don't add empty fields to this array

**Comment by johnrix** [comment]
Beware of trailing white-space characters on your email inputs also, when trying to update records. This triggers the same very misleading error message!

**Comment by mattmintun** [comment]
This is super helpful! Came up with the same issue myself with having a capital character in the email address. Now i'm `$memberEmail = strtolower($memberEmail);` anytime I'm communicating with Mailchimp via API. Tested and WORKING! Thanks for bringing this to light @Jossnaz

**Comment by lakinmohapatra** [comment]
$result = $mailChimp->get("lists/$listId/members/$subscriberHash"); 
Its showing 404 error. Please help

**Comment by andrii-pukhalevych** [comment]
I thinkt its preferred to use `mb_strtolower`, because emails may have mulibyte characters

**Comment by jiblett1000** [comment]
This is an old thread, but for anyone stumbling on this, using this api method worked for me, rather than just using `addListMember`:

https://mailchimp.com/developer/marketing/api/list-members/add-or-update-list-member/

**Comment by Asparagirl** [comment]
^ The problem with that version is that it does not seem to accept adding tags to a new or existing list member.

**Comment by zagarskas** [comment]
This is still wired in the worst way possible, requiring multiple functions to pull off a simple task: When needing to ADD or UPDATE a member on a list only 1 API call should be needed.

When using the POST method `$api->post("lists/$_mc_list/members"`
sure, new users can be added, but a 400 failure occurs if they submit twice and update a preference, name, phone or a tag.

However, when using the PUT method `$api->put("/lists/$_mc_list/members/$email"`
the update works for an existing user, but a 400 failure occurs when a new user is added

Why would anyone build an API like this?
Its like making a door that only opens backwards. 
Doors should swing both ways. In and out.

This could be 1 simple function that handles all of the following:

- If the user does not exist => make them
- If the user does exist => update them
- done.

Allow me to convince you with a real world example:
Wedding service website, user signs up, a POST API call is made, their fname/lname/email is added. Few months later same user wants to update their info after the ceremony -but- when they update their profile the local website DB is updated, but the API call to MailChimp fails. 

Those users then have to be tracked down, manually, in Mailchimp and edited by hand. Their first name, last name, email and related tags (married, single, engaged, ect) must be edited one person at a time (after they complain). Its also rude to then have their name be incorrect after they already edited it. A tragic loss of human life, wasted time, on a thing that should already work.

- When running a PUT the users **fname/lname/email are never changed** 
- When running a POST the 400 error occurs, **preventing an update**
- (updating the address, phone number and tags also **does not work**)

This does not make sense. **Why would it be wired this way?**
This is but 1 example. 

Try to use PUT and POST to update: fname, lname, email, address, tags and phone => it fails. It should not.

Expected behavior: When either a POST or PUT call with a valid API key => **all data sent over should be honored.**

**Comment by johnrix** [comment]
@zagarskas, while I thoroughly agree with your assessment of the absurdity of the API arrangement, I think you are barking up the wrong tree by posting it here. As the repo owner alluded to earlier in this thread, this is just a thin non-abstracted PHP wrapper around the MailChimp API, so it is MailChimp rather than @drewm that you need to hit with the concern. I'm totally behind you there though!
