### ISSUE TITLE
Passing through PROXY

### ISSUE THREAD

**Issue by leocaseiro** [drewm/mailchimp-api#32]
I'm using this class and in my office and we have to connect CURL through a proxy, I added a method to set up a proxy. It might be useful for somebody else.

**Comment by leocaseiro** [comment]
Nice feedback... I hope you're not part of MailChimp team.

**Comment by drewm** [comment]
I don't know what would lead you to think I have anything to do with MailChimp.

I closed this because it was an unsolicited PR, and nobody else supported it. If you're the only one who needs this feature, then you're best to maintain your own branch with the feature - otherwise it becomes code debt that you're asking me to maintain.

**Comment by leocaseiro** [comment]
Thank you for your feedback. I was just wondering if someone was maintaining this lib(6 months on silence) and suddenly the issue was closed without any feedback. I'm happy to maintain my branch.

**Comment by Goues** [comment]
Please reopen this issue, we would like to use proxy too. It is a common feature for libraries using cURL.

**Comment by Tamarpe** [comment]
I need that feature too, would be nice to have it commited
