### ISSUE TITLE
Using with php 5.2.17 - Can I? How? Server set.

### ISSUE THREAD

**Issue by WriterStat** [drewm/mailchimp-api#50]
Hi! I have a need to use a simple php mailchimp wrapper quick for subscribing users to lists and sending an intro campaign.  Depending on the data entered.

My server is set at php 5.2.17 and can't change it for the moment.

Can I use this?  It's basically the best last stable still used by a lot, before moving to 5.3+ for most servers.

Are there php 5.3 dependencies I can change?  Or should I try it as is?

Thanks very much for any information, help, light you can shed on this.  Can't make them move quite yet.

Best,

-C

**Comment by WriterStat** [comment]
No one seems to be responding with info.

So to those that read this after, here's what I did to make it work.

With that said. For anyone having troubles with this in any version of PHP.

I commented this line out in the MailChimp.php file that comes with this archive.

//namespace Drewm;

After doing that everything worked fine, in any version of PHP.  It really doesn't need the line of code above, if you are dropping this into your PHP code, where well MailChimp.php is set to create a class of $mailchimp or even $MailChimp.

Unless you are using multiple different MailChimp abstractions, all with the same variable and class names etc...

But who really would use multiple different MailChimp abstractions, that do the exact same things anyways?  One abstraction library is more than enough. =)))

As well a collision is sort of hard to do, if you are including/requiring this abstraction file and not another one exactly like it after it.  I guess except for those folks naming their own created software MailChimp already. 

For an abstraction created for brevity, this seems a bit well, over kill.  And could be initially commented out.

Hope this helps someone.

With that said the author prolly had his reasons. So could be justified on larger projects.  Maybe just not needed for the large majority.

Much Thanks to the author for the quick curl/file get requests.  Makes this smaller than the official files.

Cheers,

**Comment by drewm** [comment]
It's because it's a small component that would commonly be dropped into larger, more complex projects where namespacing is helpful, expected, and best practise. 

If you're still running PHP 5.2 then that's your lookout. You can't expect others who are already giving you stuff for free to accommodate your problems.

**Comment by WriterStat** [comment]
Woah! Kinda cranky aren't we? =)))  Yikes.  I create a lot of software for free for people to use.  And I wouldn't have responded this way.  Instead I would have dropped me a note.  Of explanation.  Originally.  A couple of days ago.  Not been this way at all. Afterwards.

And well I would have let me close this.  It still stands correctly as the solution.

I didn't say anything detrimental to you.  I just echoed your statements above and highlighted them.  If you read it.  However, it ONLY becomes a problem if someone in your group of crack developers can't remember what or that they are using 2 basically identical libraries etc...

If that's the case, I'd want the software to scream and tell me, so I could get rid of one.  Or fix the duplicate code etc...  The collision code.  Not cover it up.  Regardless of what it was.

Namespaces are definitely cool when you expect duplications of code/codenames etc...especially in javascript cases where this is likely for large libraries of code with duplicate functionality.  Not as likely here.  No big library, just one generic call over the net really. Important yes, large, well no.

I wouldn't want it to be covered up by a namespace, namespace problem later on in that big old complex code with duplications etc...  Nor would I suppose would you.  Or your supervisor.

Again my opinion, you could help yourself by having a bit of documentation.  Allowing folks to comment this in or out on their need.  For different versions of PHP.

Cuz prolly not needed in 95% of everything. =)

Again sir, your response was unwarranted.  I wasn't bagging you.  Creating open source software means yeah you want to accommodate people.  I do as does everyone else I know.  Since well PHP 5.2.17 and many other flavors are still being used in thousands of hosted servers worldwide.  Yes I know silly, but true.

And with that said I didn't ask you to accommodate me in any way. I only opinioned adding that in causes some things and could be commented out. And that in most practical projects prolly not needed.  Unless you have duplicates. which would also be bad.

It's basically a vanity namespace.

With that said I do appreciate the code.  I added a config file to it, so that I didn't have to duplicate the keys, list ids etc... for it every where.  It might be a small but good addition to the code.

Cheers and thank you!

**Comment by WriterStat** [comment]
Again sir, your response was unwarranted.  I wasn't bagging you.  Creating open source software means yeah you want to accommodate people.  I do as does everyone else I know.  Since well PHP 5.2.17 and many other flavors are still being used in thousands of hosted servers worldwide.  Yes I know silly, but true.

And with that said I didn't ask you to accommodate me in any way. I only opinioned adding that in causes some things and could be commented out. And that in most practical projects prolly not needed.  Unless you have duplicates. which would also be bad.

It's basically a vanity namespace.

With that said I do appreciate the code.  I added a config file to it, so that I didn't have to duplicate the keys, list ids etc... for it every where.  It might be a small but good addition to the code.

Cheers and thank you!

**Comment by drewm** [comment]
Let me explain how you pissed me off. You're clearly not aware how your actions have led to my response. Sorry if this sounds overly direct, but I need to be direct so that you understand.

For context, we're talking about one file of less than 100 lines of PHP code. I've shared it here in case it's useful, but seriously, any PHP developer could put this together themselves. Nowhere have I said that I'll provide you with support in using it, modifying it or getting it working on some crappy old server that needs upgrading. Here it is, use it or not.

So you raise an issue against the code with your opening gambit:

> Can I use this? [...] Are there php 5.3 dependencies I can change? Or should I try it as is?

Again this is one file, less than 100 lines of code. You were so close. Why should I have to stop what I'm doing to analyse your situation for you? Why did you spend the time creating an issue at all? *Just try it.* I am not your mother.

I ignored your issue because I was busy with my own work. I don't owe you anything, remember. Then you followed up with:

> No one seems to be responding with info.

And now I'm actually pissed off. Of course no one is responding with info, because your request is lazy. Take the hint.

I'm really not interested in your personal views on the relevance of namespaces. The simple fact is that when sharing PHP code with others then best practise dictates that it uses a unique namespace. That's just the way it is, whether you or I agree with it or not. I'd recommend reading http://www.phptherightway.com

And sure, there are lots of people running PHP 5.2. There are also lots of people driving without insurance. I'm not going to recommend or assist with either.

As your second response shows, you were capable of figuring out what you needed to do. If you'd stopped to think and to spend a few moments trying a solution first, then you wouldn't have needed to raise the issue at all, let alone complain that you didn't get a response. That's why I'm pissed off. Have a little bit more respect for other people's time and you might get better results when you really do need help.

Best of luck with your project, and do think about upgrading that server. PHP 5.4 hits end-of-life in one month from today.
