### ISSUE TITLE
Return Blank...

### ISSUE THREAD

**Issue by webdev20** [drewm/mailchimp-api#58]
I am not even able to get `lists` using the example shown on the doc. I wrap the instantiation inside a class.

**Comment by giovannipds** [comment]
Same thing here...

**Comment by drewm** [comment]
You've not provided any information that would enable anyone to help you.

**Comment by tobya** [comment]
I had the same issue and found it seems to be an issue with verifying the Mailchimp SSL server.

If you modify in MailChimp.php

    private $verify_ssl   = true;

to

     public  $verify_ssl   = true;

then call your code like this

    $MailChimp->verify_ssl = false;           
    print_r($MailChimp->get('lists'));

This may not be a secure solution.  However when curl is unable to verify the peer and is requested to do so it appears to raise no error.

**Comment by giovannipds** [comment]
Hello @drewm. I was trying to test the example that is at the docs:

    <?php

    require 'vendor/autoload.php';

    $MailChimp = new \Drewm\MailChimp('---> MY KEY HERE <---');
    echo '<pre>';
    print_r($MailChimp->call('lists/list'));

But it was returning nothing, a blank page. Trying it again today, it has returned an array with the correct informations.

Testing what @tobya said, it's exactly that, when verify_ssl is true, it returns nothing to me. What is weird is that you haven't done any recently modifications at the code, lol.

Best wishes to all.

**Comment by tobya** [comment]
I think the issue is more likely to be with Mailchimps ssl cert which may have changed recently.

**Comment by BorisAdams** [comment]
The same issue in July 2021. I'm in Australia, in case that makes any difference to the certificates.

It was fixed with @tobya's tip... `$MailChimp->verify_ssl = false;  `

No need to change MailChimp.php, as `verify_ssl` is now public.

Quite a relief, as I liked the look of this library, but am utterly new to the MailChimp API so without this solution I was stuck and would have had to abandon it! Thanks, @tobya , from Australia!
