### ISSUE TITLE
SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by mmoustafa** [drewm/mailchimp-api#76]
Is this a persistent cURL issue with the HTTPS Mailchimp api endpoint? Or is it just me. I changed the MailChimp.php to point to the HTTP endpoint and it worked fine.

**Comment by mmoustafa** [comment]
If there's a way to turn off SSL verification without editing class code, that would be perfect.

**Comment by nesmyslny** [comment]
I just had the same problem. Though this issue is closed, I add my solution here.

[Here](http://redwebturtle.blogspot.de/2013/09/mailchimp-api-v20-ssl-error-solution.html) is explained, that one solution is to set `CURLOPT_SSL_VERIFYPEER` to false (like that `curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);`)

mailchimp-api exposes `$verify_ssl` to exactly control this flag:

```php
$mailchimp = new MailChimp($apiKey);
$mailchimp->verify_ssl = false;
```

**Comment by terrymun** [comment]
Turning of SSL peer verification is dangerous. You're basically solving the problem of badly made house keys by leaving your front door wide open :(

**Comment by nesmyslny** [comment]
Yes, sure. Thanks for this clarification!
I had this issue with my development environment. So I think there are valid reasons to disable it. At least one ;)

**Comment by drzraf** [comment]
Similarly the current solution consist in installing a (somehow
breakable) certificate system-wide (and depending upon root privileges)
instead of restricting it at the application-scope by simply bundling it ;)
