### ISSUE TITLE
PHP Notice :     Undefined index: request_header	

### ISSUE THREAD

**Issue by whipsterCZ** [drewm/mailchimp-api#78]
On Mailchimp:220

```
$this->last_request['headers'] = $response['headers']['request_header'];
```

**Comment by drewm** [comment]
I'm going to need more information if you want me to help.

**Comment by TimE90** [comment]
Same here. Class doesn't work anymore.. :(

**Comment by drewm** [comment]
Provide me with some information so I can help.

**Comment by TimE90** [comment]
We do nothing more than the regular get(list) but get the above Warning and no response:


$MailChimp = new MailChimp('APIKEY-us12');
$result = $MailChimp->get('lists');
print_r($result);

**Comment by whipsterCZ** [comment]
same as TimE90.

**Comment by drewm** [comment]
Which version of PHP are you using? Which version of curl? Are you using the master branch?

**Comment by Sudei** [comment]
I just had the same error on my Windows Env - PHP 5.5.

I juste use `echo $mailChimp->getLastError();` and found it was because of SSL Verification.

You can disable if you're on dev and windows by : 
```
$MailChimp = new MailChimp('APIKEY-us12');
if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') {
    $MailChimp->verify_ssl = false;
}
```

@drewm - Would you like to add this feature in the construct of your Class ? Do you want me to create a pull request ?

**Comment by ikristher** [comment]
@Sudei Thank you so much. I think @drewm should include this on the constructor

**Comment by Sudei** [comment]
I think about it and I have concluded the following :

This error is due to a misconfiguration of our environment (Windows in this case).

I think the best approach shouldn't be to alter the current Class to avoid this kind of bug.
We just should inform dev. about that know issue.

Maybe @drewem should add a #know issues section on the readme and add this case as a warning and give a solution to avoid it.

What do you think about it ?

**Comment by drewm** [comment]
Please see the Troubleshooting section in the readme, which covers this.

https://github.com/drewm/mailchimp-api#troubleshooting
