### ISSUE TITLE
Batch put doesn't add member.

### ISSUE THREAD

**Issue by Vennik** [drewm/mailchimp-api#90]
It seems like the batch put doesn't add any members (update works though). Not sure if it's an issue with MailChimp or with this wrapper.

Method:
```
"lists/{$listID}/members/{$hash}"
```

**Comment by alebargut** [comment]
I've being struggling trying using the Batch method for a couple of days. I try first with my own functions and later with this wrapper. In either case I can get my batches requests to go through but all operations will fail with this error:

{
      "status_code": 404,
      "operation_id": null,
      "response": {
         "type": "http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/",
         "title": "Resource Not Found",
         "status": 404,
         "detail": "The requested resource could not be found.",
         "instance": ""
      }
   },

I have try with PUT and POST to update list with members but I always get errors. Mailchimp support says:

Alejandro, 

Thank you so much for writing back with that information. Since your first email, we were able to do some testing on our end, and we are finding that a lot of POST calls are producing that error message, even for valid POST calls.  We've been able to replicate these findings that you are seeing.

It looks like when the same POST command is being made with the same parameters and values, they are successful. The action only fails when it is used in a batch operation. We have not found out why this is happening just yet, but we have brought the issue to the attention of our developers. To set the right expectation, while they are working towards a solution, we would not be able to provide an estimated time frame for their progress as we have not yet determined why this behavior is occurring.

However, in the meantime, I recommend making the POST calls as regular calls, rather than inside batch operations. Alternatively, you are able to use the API v2.0 in the meantime if you need to make a bunch of POSTs at once.  If you are making the same calls outside of batch operations and still seeing an error, feel free to reach back out and let us know. We'll be happy to troubleshoot this further. Additionally, if you think of anything that may help with this issue, let us know.

We'll keep an eye out for your response.

Thank you,
Josephine


Has any body been successful with this?

**Comment by drewm** [comment]
It sounds very much like MailChimp are admitting it's a problem at their end.

**Comment by jonlow** [comment]
I'm also adding a user to a list (not using bash), and getting the following internal server error:

type: about:blank
response: Internal Server Error
exception: 9b5827785cda110dce282058b7596e6a
detail:  A deep, internal error has occurred during the processing of your request. Please contact support.
instance: 56a4cc8f-1004-470b-9755-be898633d4e6
status: 500
title: Internal Server Error
type: about:blank

Dropped them an email and waiting on response. Reverting to v2 for now :(

**Comment by alebargut** [comment]
Just a quick update with what they answered:

Hey Alejandro,

Thanks for getting back to us with those details, our developers have been hard at work at identifying why these POST calls were having trouble, and just recently they were able to push a fix that has resolved these issues with POST calls in these batch operations.  To address your earlier question, while we don't rate limit, attempting to send large numbers of requests is best done through batches, as they are more robust.

Could you attempt to re-send these batch calls with the original POST methods you were using beforehand?  If you are continuing to see errors after resending this with the original POST versions, please don't hesitate to reply back and we'll be glad to continue investigating.

Thank you,
Roman



Everything is working OK now.

**Comment by jonlow** [comment]
Resolved my above issue by not using the example.com email address from the README. 

All good!

**Comment by dc001** [comment]
This is my first post on github so hopefully I'm following the rules ok. 

I've also noticed some changes recently to my implementation of  Super-simple, minimum abstraction MailChimp API v3 wrapper. Everything had been working great for a number of weeks. I was able to retrieve lists, members, activity, campaigns.... 

About a week or so ago i noticed the campaign stats were failing with a 500 internal error. I checked a second implementation of the wrapper in a different project and the same thing was happening; campaign stats were failing but list, activity and members data were still being returned as expected. 

I changed the end point of my request for campaigns from: 

######
$campaigns = $MailChimp->get("lists/$list_id/campaigns");
######

to: 

######
$campaigns = $MailChimp->get("campaigns");
######

And my campaign request started working again. 

I hope this helps someone who may be experiencing a similar issue. 

On a second note, 

I am also now experiencing issues with deleting members.  Add / Update members still work as expected. However, deleting a member is failing partially (see screenshot attached). Only my custom name field is being deleted. The subscribers email address etc remains in my list.

My endpoint has not changed and is per the documentation: 

######
$MailChimp->delete("lists/$list_id/members/$subscriber_hash");
######

![screen shot 2016-04-07 at 03 35 32 2](https://cloud.githubusercontent.com/assets/3467064/14339760/366cac26-fc79-11e5-9282-0c30d3690ffd.png)

Whilst i appreciate there are minor issues to be resolved (most likely due to changes MailChimp's end) i would like to take the opportunity to say a big thank you to Drew and everyone else who has contributed. I have aggregated and visualised (using Google Graphs API) various datasets using this wrapper, which have offered an extremely insightful perspective, particularly with trending.  

Also doing some other cool stuff with the datasets, like exporting in pseudo MS Excel format. 

As a result, I've integrated the wrapper into a Content Delivery System I'm looking to release end of the summer.  

Keep up the good work, 

Darren

![screen shot 2016-04-07 at 04 34 57 2](https://cloud.githubusercontent.com/assets/3467064/14339990/c7819fa4-fc7a-11e5-9555-2ac917db7022.png)

![screen shot 2016-04-07 at 04 36 23 2](https://cloud.githubusercontent.com/assets/3467064/14340001/daeb81ea-fc7a-11e5-8444-56db23543771.png)

**Comment by drewm** [comment]
@dc001 All the wrapper does is ferry your messages back and forth to the MailChimp API. We don't control the end points or the behaviour. You should raise your issues with MailChimp directly.

**Comment by dc001** [comment]
Hi Drew, thanks for the reply. I opened a ticket with MailChimp the day i first experienced the issue.  The dialogue is ongoing, with nothing of note to feedback at this stage. 

With regards my issue with Delete, you can confirm there has been no change to the lists/$list_id/members/$subscriber_hash endpoint we call when using the wrapper? 

Apologies for posting in the wrong thread earlier, i wasn't aware there was more than one, i could just see the open thread (#90) when i landed on the page.

**Comment by Vennik** [comment]
It seems that MailChimp api v3 has still a lot of problems internally. Currently MailChimp is trying to solve my issue, but apparently it's hard.

**Comment by drewm** [comment]
@dc001 The wrapper doesn't have any endpoints of it's own. If the end point you're using has changed, that's a change in the MailChimp API.

**Comment by dc001** [comment]
Many thanks for your prompt reply Vennik, it's appreciated. 

I share the same sentiment. I'll refrain from making any changes and wait for their response.

**Comment by dc001** [comment]
Thanks for the reply Drew. 

Indeed, i understand that. I just wanted to double check you were not aware of any changes that they may have made recently and / or the documentation on using the wrapper not yet updated. However, It sounds like everything is as it should be and that I'm calling the endpoint correctly. As suggested, it sounds like an issue MC's end that needs fixing. 

Again, I thought it may useful to clarify this point just in case anyone else is experiencing the same issue.

When i get a resolution from MailChimp support desk i shall update the thread.

Cheers

**Comment by dc001** [comment]
Update on Delete Member issue: 

Hey Darren,

Thanks so much for providing those additional details. That was super helpful.

**To clarify what you're seeing, we recently made changes to how we handle deleted subscribers. While we remove those subscribers from the list in the app and remove all of their associated merge data, we keep the actual address on the list with a blank status.** This helps bounce and unsubscribe requests occur for those subscribers, even after they've been deleted from the list.

As such, if you make a GET request directly to the /lists/{list_id}/members/{subscriber_hash} endpoint, you'll receive a 404 error since that subscriber has been deleted. **However, when making a GET request to the /lists/{list_id}/members endpoint, those subscribers will be included in the results with just their email address and a blank status. **

That being said, if you're seeing deleted subscribers returned at the /lists/{list_id}/members/{subscriber_hash} endpoint or with a status that isn't blank, definitely let us know and we'll be happy to continue troubleshooting. 

Cheers,
Steff

**Comment by stefanw** [comment]
For anyone getting the same error still: don't submit "@example.org" or "@example.com" addresses to Mailchimp's API. This makes testing more difficult, but it works if you replace it with a different domain (preferrably one you own).

**Comment by Vennik** [comment]
MailChimp fixed their internal bug, so this is solved.
Apparently it is normal to release a new API filled with bugs.
